#!/usr/bin/python

import pexpect 
import getpass
import sys
import time
import getopt
import re
import time

if len(sys.argv) > 2:
	options, remainder = getopt.getopt(sys.argv[1:], 'i:l', ['ifile=','log'])
	print(options)
	for opt, arg in options:
		if opt in ('-i', '--ifile'):
			ipaddy = open(arg, "r")
			print(arg)
			hosts = ipaddy.readlines()
			print(hosts)
		elif opt in ('-l', '--log'):
			log = file('./mylog','w+') 
		else:
			log = file('./mylog','w+')
	log = file('./mylog','w+')
	print log 
if len(sys.argv) < 2:
	hosts = []
	hosts.append(raw_input('Enter SSH IP Address: '))

int2up=open('./interfaceup', 'w')
ssh_newkey = 'Are you sure you want to continue connecting'
user = 'tom'
passwd = getpass.getpass("Enter Password: ")
en = getpass.getpass("Enter Enable Password: ")

for host in hosts:
	ssh = pexpect.spawn ("ssh " + user + "@" + host)
	#ssh.logfile= something i dont know its not working.
	i=ssh.expect([ssh_newkey,'.*assword:.*',pexpect.EOF,pexpect.TIMEOUT],5)
	if i==0:
		print "Accepting Key"
		ssh.sendline('yes')
		i=ssh.expect([ssh_newkey,'.*assword:.*',pexpect.EOF,pexpect.TIMEOUT],5)	
	if i==1:
		print "expect gave your password"
		ssh.sendline(passwd)
	elif i==2:
		print "I can't do shit"
		pass
	elif i==3:
		print "timeout"
		pass

	ssh.expect ('.*>.*')
	ssh.sendline ('ena')
	ssh.expect ('.*assword:.*')
	ssh.sendline (en)

	i=ssh.expect (['.*#.*','.*>.*'])
	if i==0:
		print "now in enable mode"
	if i==1:
		print "wrong enable password.  Exiting ssh session"
		int2up.write(host, 'wrong enable')		
		ssh.sendline("exit")
		exit()
	print host
	ssh.sendline("conf t")
	ssh.expect('.*config.*')
	ssh.sendline('no interface vlan 41')
	ssh.expect('.*#.*')
	ssh.sendline(" ")
	print ssh.after
	ssh.sendline('end')		
	ssh.sendline("write")
	ssh.sendline('exit')
#	
	print "done with host moving to next router"

sys.exit()






